aqi:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('PG_HOST', 'localhost') }}"
      user: aqi
      password: aqi
      dbname: aqi
      schema: public
      port: "{{ env_var('PG_PORT', '5434') | as_number }}"
      threads: 4
